"""Audio scripter — generates a two-host dialogue script from notebook sources.

Produces a structured JSON of alternating ``Host A`` / ``Host B`` utterances
with natural transitions, references to the sources, and a target duration of
~5-8 minutes (FR-71). The dialogue is generated by the single in-app model
``gemma4:31b-cloud`` via Ollama Cloud.

In mock mode, a deterministic canned dialogue is returned (offline, no LLM call).
"""

from __future__ import annotations

import hashlib
import json
import logging
import re

from src.extensions import db
from src.models import Notebook, Source
from src.repositories import content_registry_repo
from src.services.ollama_client import get_ollama_client

logger = logging.getLogger(__name__)

_MD_FENCE_RE = re.compile(r"```(?:json)?\s*\n?(.*)\n?```", re.DOTALL)


def _strip_markdown_fences(raw: str) -> str:
    """Strip markdown code fences (```json ... ```) that LLMs often wrap JSON in.

    Also handles cases where the LLM omits the closing fence or adds trailing text.
    """
    text = raw.strip()
    m = _MD_FENCE_RE.search(text)
    if m:
        return m.group(1).strip()
    # If the text starts with a fence but has no closing fence, strip the opening.
    if text.startswith("```"):
        first_newline = text.find("\n")
        if first_newline != -1:
            return text[first_newline + 1 :].strip()
    return text


DIALOGUE_SYSTEM_PROMPT = (
    "You are a creative assistant that produces engaging two-host podcast dialogues. "
    "Given source texts, write a natural conversation between Ava and Andrew "
    "that summarizes and discusses the key points. "
    "{duration_instruction}"
    "The hosts should alternate turns, reference the sources naturally, and keep it engaging. "
    "Ava should introduce herself as Ava, and Andrew should introduce himself as Andrew. "
    "Never use generic labels like 'Host A' or 'Host B' — always use their real names. "
    'IMPORTANT: In the JSON, use "host": "A" for Ava and "host": "B" for Andrew. '
    'Respond as JSON: {{"dialogue": [{{"host": "A", "text": "..."}}, '
    '{{"host": "B", "text": "..."}}, ...]}}'
)


def _build_duration_instruction(min_sec: int, max_sec: int, total_chars: int) -> str:
    """Build a duration instruction for the dialogue prompt.

    Computes a target word count from source material size:
    ~150 chars ≈ 1 second of speech, ~2.5 words per second.
    """
    target_sec = min(max_sec, max(min_sec, total_chars // 150))
    target_words = target_sec * 2.5
    return (
        f"The dialogue should be about {target_sec} seconds when spoken "
        f"(~{int(target_words)} words). "
    )


_HOST_TEXT_RE = re.compile(
    r'"host"\s*:\s*"([^"]+)"\s*,\s*"text"\s*:\s*"',
    re.DOTALL,
)


def parse_dialogue_response(raw: str) -> list[dict[str, str]]:
    """Parse the LLM's JSON response into a list of utterances.

    Each utterance: ``{"host": "A"|"B", "text": "..."}``.
    Filters out empty-text entries. Normalizes host labels to A/B.
    Handles markdown code fences (```json ... ```) that LLMs often wrap JSON in.
    Falls back to structural extraction if JSON is malformed (unescaped quotes in text).
    """
    if not raw:
        return []
    cleaned = _strip_markdown_fences(raw)

    try:
        data = json.loads(cleaned)
        return _build_utterances(data.get("dialogue", []))
    except (json.JSONDecodeError, TypeError):
        pass

    result = _extract_utterances_structural(cleaned)
    if result:
        return result

    logger.warning("All parsing methods failed for dialogue response")
    return []


def _build_utterances(raw_dialogue: list[dict[str, str]]) -> list[dict[str, str]]:
    """Build utterance list from parsed JSON dialogue array."""
    if not isinstance(raw_dialogue, list):
        return []
    result: list[dict[str, str]] = []
    for item in raw_dialogue:
        if not isinstance(item, dict):
            continue
        text = str(item.get("text", "")).strip()
        if not text:
            continue
        host = _normalize_host(str(item.get("host", "A")))
        result.append({"host": host, "text": text})
    return result


def _extract_utterances_structural(text: str) -> list[dict[str, str]]:
    """Extract utterances from malformed JSON by finding host/text structural markers.

    Finds each ``"host": "X", "text": "`` marker and captures the text until the
    next marker or the closing ``"}`` / ``"}]`` of the dialogue array.
    """
    result: list[dict[str, str]] = []
    matches = list(_HOST_TEXT_RE.finditer(text))
    if not matches:
        return result

    for i, m in enumerate(matches):
        host = _normalize_host(m.group(1))
        start = m.end()
        # Find the end: next host marker, or closing of this utterance object.
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        chunk = text[start:end]
        # Strip trailing `"}`, `"},`, `"}]`, etc.
        chunk = re.sub(r'\s*"\s*\}[\s,\]]*$', "", chunk)
        utterance_text = chunk.strip()
        if utterance_text:
            result.append({"host": host, "text": utterance_text})

    if result:
        logger.info("Structural extraction recovered %d utterances", len(result))
    return result


def _normalize_host(raw: str) -> str:
    """Normalize various host labels to 'A' or 'B'."""
    lower = raw.lower().strip()
    if lower in ("a", "host_a", "host a", "1", "first", "left", "ava"):
        return "A"
    return "B"


def write_dialogue(notebook: Notebook, topic: str = "") -> list[dict[str, str]]:
    """Generate a two-host dialogue script for the notebook.

    Returns a list of ``{"host": "A"|"B", "text": "..."}`` dicts.
    Empty list if no sources or generation fails.
    """
    scripter = AudioScripter()
    return scripter.write_dialogue(notebook, topic=topic)


class AudioScripter:
    """Generates two-host dialogue scripts via Ollama Cloud (or mock)."""

    def __init__(self) -> None:
        from src.config import Config

        self._config = Config()
        self._client = get_ollama_client()

    def write_dialogue(self, notebook: Notebook, topic: str = "") -> list[dict[str, str]]:
        """Generate the dialogue script."""
        source_texts = self._get_source_texts(notebook.id)
        if not source_texts:
            logger.info("No sources for notebook %d; dialogue is empty", notebook.id)
            return []

        if self._client._mock:  # noqa: SLF001
            return self._mock_dialogue(notebook.id, source_texts)

        try:
            total_chars = sum(len(t) for t in source_texts)
            duration_instruction = _build_duration_instruction(
                self._config.audio_min_duration_seconds,
                self._config.audio_max_duration_seconds,
                total_chars,
            )
            system_prompt = DIALOGUE_SYSTEM_PROMPT.format(
                duration_instruction=duration_instruction,
            )

            user_content = (
                "Write a two-host podcast dialogue based on these source texts:\n\n"
                + "\n\n".join(source_texts[:3])
            )
            if topic:
                user_content = f"Focus the discussion on: {topic}\n\n" + user_content

            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ]
            raw = self._client.chat(messages)
            logger.info(
                "Dialogue LLM response: %d chars, first=%.100s...",
                len(raw),
                raw[:100],
            )
            dialogue = parse_dialogue_response(raw)
            if not dialogue:
                logger.warning(
                    "parse_dialogue_response returned empty for notebook %d. "
                    "Raw response: %.300s...",
                    notebook.id,
                    raw[:300],
                )
            dialogue = self._ensure_alternation(dialogue)
            return dialogue
        except Exception as exc:  # noqa: BLE001
            logger.error("Dialogue generation failed for notebook %d: %s", notebook.id, exc)
            return []

    def _get_source_texts(self, notebook_id: int) -> list[str]:
        """Return cached extracted texts from the ContentRegistry."""
        sources = (
            db.session.query(Source)
            .filter(
                Source.notebook_id == notebook_id,
                Source.status.in_(["ready", "partial"]),
            )
            .all()
        )
        texts: list[str] = []
        for s in sources:
            entry = content_registry_repo.get_by_hash(s.content_hash)
            if entry and entry.extracted_text:
                texts.append(entry.extracted_text)
        return texts

    @staticmethod
    def _ensure_alternation(
        dialogue: list[dict[str, str]],
    ) -> list[dict[str, str]]:
        """Ensure hosts alternate A, B, A, B... by fixing consecutive same-host entries."""
        if not dialogue:
            return dialogue
        result: list[dict[str, str]] = []
        expected = "A"
        for entry in dialogue:
            if entry["host"] != expected:
                entry = {"host": expected, "text": entry["text"]}
            result.append(entry)
            expected = "B" if expected == "A" else "A"
        return result

    @staticmethod
    def _mock_dialogue(
        notebook_id: int,
        source_texts: list[str],
    ) -> list[dict[str, str]]:
        """Deterministic canned dialogue for mock mode."""
        digest = hashlib.sha256(f"{notebook_id}:{source_texts[0][:50]}".encode()).hexdigest()[:8]
        return [
            {
                "host": "A",
                "text": (
                    f"Welcome to the audio overview! Today we're discussing "
                    f"the key points from your sources. [{digest}]"
                ),
            },
            {
                "host": "B",
                "text": (
                    "That's right! The documents cover some interesting topics. "
                    "Let me start with the main themes."
                ),
            },
            {
                "host": "A",
                "text": (
                    "Based on the sources, the primary focus seems to be on "
                    "the concepts and relationships described in the text."
                ),
            },
            {
                "host": "B",
                "text": (
                    "Exactly. And there are several important details worth "
                    "highlighting for our listeners."
                ),
            },
            {
                "host": "A",
                "text": "Let's wrap up by summarizing the key takeaways. Thanks for listening!",
            },
            {
                "host": "B",
                "text": "Thank you! We hope this overview was helpful. See you next time!",
            },
        ]
