"""Summary service — auto-generated summary + suggested questions.

Generates a short summary (<=150 words) + 5 suggested questions when a
notebook is created or sources change. Idempotent: a job keyed by
``(notebook_id, content_signature)`` skips re-run if the signature is
unchanged (FR-60, FR-61, FR-62).

The summary is generated by the single in-app model ``gemma4:31b-cloud``
via Ollama Cloud. In mock mode, deterministic canned output is returned.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass

from src.extensions import db
from src.models import Notebook, Source
from src.repositories import content_registry_repo
from src.services.ollama_client import get_ollama_client

logger = logging.getLogger(__name__)

_MD_FENCE_RE = re.compile(r"```(?:json)?\s*\n?(.*?)\n?```", re.DOTALL)


def _strip_markdown_fences(raw: str) -> str:
    """Strip markdown code fences (```json ... ```) that LLMs often wrap JSON in."""
    m = _MD_FENCE_RE.search(raw)
    if m:
        return m.group(1).strip()
    return raw.strip()


SUMMARY_SYSTEM_PROMPT = (
    "You are a helpful assistant that summarizes documents. "
    "Given the source texts, produce a concise summary (max 150 words) "
    "and 5 suggested questions a user might ask. "
    'Respond as JSON: {"summary": "...", "suggested_questions": ["q1", ...]}'
)

EMPTY_SOURCES_PLACEHOLDER = "No sources have been uploaded yet."


@dataclass
class SummaryResult:
    """Outcome of summary generation."""

    summary: str
    suggested_questions: list[str]
    skipped: bool


def compute_content_signature(content_hashes: list[str]) -> str:
    """Return a deterministic hash of sorted content hashes (idempotency key)."""
    sorted_hashes = sorted(content_hashes)
    combined = "|".join(sorted_hashes)
    return hashlib.sha256(combined.encode("utf-8")).hexdigest()


def parse_summary_response(raw: str) -> tuple[str, list[str]]:
    """Parse the LLM's JSON response into (summary, suggested_questions).

    Falls back to returning the raw text as the summary if JSON parsing fails.
    Truncates suggested questions to 5.
    Handles markdown code fences (```json ... ```) that LLMs often wrap JSON in.
    """
    if not raw:
        return "", []
    cleaned = _strip_markdown_fences(raw)
    try:
        data = json.loads(cleaned)
        summary = data.get("summary", "")
        questions = data.get("suggested_questions", [])
        if not isinstance(questions, list):
            questions = []
        return str(summary), [str(q) for q in questions[:5]]
    except (json.JSONDecodeError, TypeError):
        logger.warning("Failed to parse summary JSON: %.200s...", cleaned[:200])
        return raw, []


class SummaryService:
    """Generates + persists notebook summaries with idempotency."""

    def __init__(self) -> None:
        self._client = get_ollama_client()

    def generate_summary(self, notebook: Notebook) -> SummaryResult | None:
        """Generate + persist a summary for the notebook.

        Returns ``SummaryResult`` or ``None`` on failure. If the content
        signature is unchanged since last generation, returns a skipped result.
        """
        # Compute current signature.
        source_hashes = self._get_source_hashes(notebook.id)
        new_signature = compute_content_signature(source_hashes)

        # Idempotency: skip if unchanged.
        if notebook.content_signature == new_signature and notebook.summary is not None:
            logger.info("Summary skipped (signature unchanged) for notebook %d", notebook.id)
            return SummaryResult(
                summary=notebook.summary,
                suggested_questions=json.loads(notebook.suggested_questions)
                if notebook.suggested_questions
                else [],
                skipped=True,
            )

        # Get source texts.
        source_texts = self._get_source_texts(source_hashes)

        if not source_texts:
            # No sources -> placeholder.
            self._persist(notebook, EMPTY_SOURCES_PLACEHOLDER, [], new_signature)
            return SummaryResult(
                summary=EMPTY_SOURCES_PLACEHOLDER,
                suggested_questions=[],
                skipped=False,
            )

        # Call LLM.
        try:
            user_content = (
                "Summarize the following source texts and suggest 5 questions:\n\n"
                + "\n\n".join(source_texts[:3])  # cap to first 3 for context
            )
            messages = [
                {"role": "system", "content": SUMMARY_SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ]
            raw = self._client.chat(messages)
            summary, questions = parse_summary_response(raw)
        except Exception as exc:  # noqa: BLE001
            logger.error("Summary generation failed for notebook %d: %s", notebook.id, exc)
            return None

        self._persist(notebook, summary, questions, new_signature)
        logger.info(
            "Summary generated for notebook %d: %d chars, %d questions",
            notebook.id,
            len(summary),
            len(questions),
        )
        return SummaryResult(summary=summary, suggested_questions=questions, skipped=False)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_source_hashes(self, notebook_id: int) -> list[str]:
        """Return content hashes for all ready/partial sources."""
        sources = (
            db.session.query(Source)
            .filter(
                Source.notebook_id == notebook_id,
                Source.status.in_(["ready", "partial"]),
            )
            .all()
        )
        return [s.content_hash for s in sources]

    def _get_source_texts(self, content_hashes: list[str]) -> list[str]:
        """Return cached extracted texts from the ContentRegistry."""
        texts: list[str] = []
        for h in content_hashes:
            entry = content_registry_repo.get_by_hash(h)
            if entry and entry.extracted_text:
                texts.append(entry.extracted_text)
        return texts

    def _persist(
        self,
        notebook: Notebook,
        summary: str,
        questions: list[str],
        signature: str,
    ) -> None:
        """Save the summary + questions + signature to the notebook row."""
        notebook.summary = summary
        notebook.suggested_questions = json.dumps(questions) if questions else None
        notebook.content_signature = signature
        db.session.commit()
