"""Summary service — auto-generated summary + suggested questions.

Generates a short summary (<=150 words) + 5 suggested questions when a
notebook is created or sources change. Idempotent: a job keyed by
``(notebook_id, content_signature)`` skips re-run if the signature is
unchanged (FR-60, FR-61, FR-62).

The summary is generated by the single in-app model ``gemma4:31b-cloud``
via Ollama Cloud. In mock mode, deterministic canned output is returned.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass

from src.extensions import db
from src.models import Notebook, Source
from src.services.context_builder import select_sources_within_budget
from src.services.llm_json import extract_json
from src.services.ollama_client import get_ollama_client

logger = logging.getLogger(__name__)

_MD_FENCE_RE = re.compile(r"```(?:json)?\s*\n?(.*?)\n?```", re.DOTALL)


def _strip_markdown_fences(raw: str) -> str:
    """Strip markdown code fences (```json ... ```) that LLMs often wrap JSON in."""
    m = _MD_FENCE_RE.search(raw)
    if m:
        return m.group(1).strip()
    return raw.strip()


SUMMARY_SYSTEM_PROMPT = (
    "You are a helpful assistant that summarizes documents. "
    "Given the source texts, produce a concise summary (max 150 words) "
    "and 5 suggested questions a user might ask. "
    'Respond as JSON: {"summary": "...", "suggested_questions": ["q1", ...]}'
)

EMPTY_SOURCES_PLACEHOLDER = "No sources have been uploaded yet."


def _normalize_title(title: str) -> str:
    """Normalize a question title for dedup (lowercase, strip parens/punct)."""
    import re
    import string

    text = (title or "").lower().strip()
    text = re.sub(r"\([^)]*\)", "", text)
    text = text.translate(str.maketrans("", "", string.punctuation))
    return " ".join(text.split())


def _is_duplicate_title(title: str, seen: list[str]) -> bool:
    """Return True when ``title`` duplicates a seen title (exact/substring)."""
    norm = _normalize_title(title)
    if not norm:
        return True
    for other in seen:
        other_norm = _normalize_title(other)
        if not other_norm:
            continue
        if norm == other_norm:
            return True
        if len(norm) >= 20 and (norm in other_norm or other_norm in norm):
            return True
    return False


def dedup_questions(questions: list[str]) -> list[str]:
    """Deduplicate suggested questions, preserving order (max 5)."""
    out: list[str] = []
    for q in questions:
        text = str(q).strip()
        if not text or _is_duplicate_title(text, out):
            continue
        out.append(text)
        if len(out) >= 5:
            break
    return out


@dataclass
class SummaryResult:
    """Outcome of summary generation."""

    summary: str
    suggested_questions: list[str]
    skipped: bool


def compute_content_signature(content_hashes: list[str]) -> str:
    """Return a deterministic hash of sorted content hashes (idempotency key)."""
    sorted_hashes = sorted(content_hashes)
    combined = "|".join(sorted_hashes)
    return hashlib.sha256(combined.encode("utf-8")).hexdigest()


def parse_summary_response(raw: str) -> tuple[str, list[str]]:
    """Parse the LLM's JSON response into (summary, suggested_questions).

    Falls back to returning the raw text as the summary if JSON parsing fails.
    Truncates suggested questions to 5.
    Handles markdown code fences (```json ... ```) and trailing prose via
    the shared ``llm_json`` helper.
    """
    if not raw:
        return "", []
    cleaned = _strip_markdown_fences(raw)
    data = extract_json(cleaned)
    if data is None:
        try:
            data = json.loads(cleaned)
        except (json.JSONDecodeError, TypeError):
            data = None
    if not isinstance(data, dict):
        logger.warning("Failed to parse summary JSON: %.200s...", cleaned[:200])
        return raw, []
    try:
        summary = data.get("summary", "")
        questions = data.get("suggested_questions", [])
        if not isinstance(questions, list):
            questions = []
        return str(summary), dedup_questions([str(q) for q in questions])
    except (TypeError, AttributeError):
        logger.warning("Failed to parse summary JSON: %.200s...", cleaned[:200])
        return raw, []


def parse_suggested_questions(raw: str | None) -> list[str]:
    """Parse stored ``suggested_questions`` JSON into a question list.

    Returns ``[]`` when the value is missing, corrupt, or not a list so a
    single bad row can never turn a read-only summary view into a 500.
    """
    if not raw:
        return []
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        logger.warning("Stored suggested_questions is not valid JSON; returning []")
        return []
    if not isinstance(data, list):
        return []
    return [str(q) for q in data]


class SummaryService:
    """Generates + persists notebook summaries with idempotency."""

    def __init__(self) -> None:
        from src.config import Config

        self._config = Config()
        self._client = get_ollama_client()

    def generate_summary(self, notebook: Notebook) -> SummaryResult | None:
        """Generate + persist a summary for the notebook.

        Returns ``SummaryResult`` or ``None`` on failure. If the content
        signature is unchanged since last generation, returns a skipped result.
        """
        # Compute current signature.
        source_hashes = self._get_source_hashes(notebook.id)
        new_signature = compute_content_signature(source_hashes)

        # Idempotency: skip if unchanged.
        if notebook.content_signature == new_signature and notebook.summary is not None:
            logger.info("Summary skipped (signature unchanged) for notebook %d", notebook.id)
            return SummaryResult(
                summary=notebook.summary,
                suggested_questions=parse_suggested_questions(notebook.suggested_questions),
                skipped=True,
            )

        # Best-effort full-coverage digests (background thread: one LLM pass
        # per changed source, cached by content hash for chat + overviews).
        try:
            from src.services.section_digest import ensure_notebook_digests

            ensure_notebook_digests(notebook.id, self._config)
        except Exception:  # noqa: BLE001
            logger.debug("Digest ensure skipped for notebook %d", notebook.id)

        # Get source texts (budgeted, ordered by upload time).
        selection = select_sources_within_budget(
            notebook.id, self._config.overview_max_context_chars
        )
        source_texts = selection.texts

        if not source_texts:
            # No sources -> placeholder.
            self._persist(notebook, EMPTY_SOURCES_PLACEHOLDER, [], new_signature)
            return SummaryResult(
                summary=EMPTY_SOURCES_PLACEHOLDER,
                suggested_questions=[],
                skipped=False,
            )

        # Call LLM. The cached section digests cover every part of every
        # source (full coverage); the budgeted raw texts add verbatim depth.
        try:
            digest_block = self._digest_block(notebook.id)
            user_content = (
                "Summarize the following source texts and suggest 5 questions:\n\n"
                + (digest_block + "\n\n" if digest_block else "")
                + "\n\n".join(source_texts)
            )
            messages = [
                {"role": "system", "content": SUMMARY_SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ]
            raw = self._client.chat(messages)
            summary, questions = parse_summary_response(raw)
            questions = self._augment_with_web(notebook, questions)
        except Exception as exc:  # noqa: BLE001
            logger.error("Summary generation failed for notebook %d: %s", notebook.id, exc)
            return None

        self._persist(notebook, summary, questions, new_signature)
        logger.info(
            "Summary generated for notebook %d: %d chars, %d questions",
            notebook.id,
            len(summary),
            len(questions),
        )
        return SummaryResult(summary=summary, suggested_questions=questions, skipped=False)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _digest_block(self, notebook_id: int) -> str:
        """Return the stitched cached digests for overview prompts ("" if cold)."""
        try:
            from src.services.section_digest import notebook_digest_text

            if not self._config.rag_summary_map:
                return ""
            return notebook_digest_text(
                notebook_id, self._config.rag_digest_max_chars, self._config
            )
        except Exception:  # noqa: BLE001
            return ""

    def _augment_with_web(self, notebook: Notebook, questions: list[str]) -> list[str]:
        """Append opt-in web-augmented questions when internal ones run short.

        Fail-closed: proprietary topics, disabled flag, mock mode, or any
        error yields the input unchanged.
        """
        try:
            if len(questions) >= 5 or not self._config.web_search_enabled:
                return questions
            from src.services.web_search_service import (
                classify_topic_source,
                synthesize_external_questions,
                web_search,
            )

            topic = f"{notebook.name} {notebook.description or ''}".strip()
            if classify_topic_source(topic) == "proprietary":
                return questions
            snippets = web_search(
                topic or notebook.name,
                max_results=self._config.web_search_max_results,
                timeout=self._config.web_search_timeout,
            )
            if not snippets:
                return questions
            external = synthesize_external_questions(topic, snippets)
            for item in external:
                title = str(item.get("title", "")).strip()
                if title and not _is_duplicate_title(title, questions):
                    questions.append(title)
                if len(questions) >= 5:
                    break
            return dedup_questions(questions)
        except Exception:  # noqa: BLE001
            return questions

    def _get_source_hashes(self, notebook_id: int) -> list[str]:
        """Return content hashes for all ready/partial sources."""
        sources = (
            db.session.query(Source)
            .filter(
                Source.notebook_id == notebook_id,
                Source.status.in_(["ready", "partial"]),
            )
            .all()
        )
        return [s.content_hash for s in sources]

    def _persist(
        self,
        notebook: Notebook,
        summary: str,
        questions: list[str],
        signature: str,
    ) -> None:
        """Save the summary + questions + signature to the notebook row."""
        notebook.summary = summary
        notebook.suggested_questions = json.dumps(questions) if questions else None
        notebook.content_signature = signature
        db.session.commit()
